import { Inter } from 'next/font/google'
import '@/core/styling/global.scss'

const inter = Inter({ subsets: ['latin'] })

import ClientApp from '@/core/app/clientApp'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientApp>{children}</ClientApp>
      </body>
    </html>
  )
}
